######################################################################
#
# File name : top_tb_wave.do
# Created on: Thu Apr 14 20:14:40 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
