######################################################################
#
# File name : top_tb_compile.do
# Created on: Thu Apr 21 16:23:35 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\Modelsim\\win64\\vlib modelsim_lib/work
E:\\Modelsim\\win64\\vlib modelsim_lib/msim

E:\\Modelsim\\win64\\vlib modelsim_lib/msim/fifo_generator_v13_2_3
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/blk_mem_gen_v8_4_2

E:\\Modelsim\\win64\\vmap fifo_generator_v13_2_3 modelsim_lib/msim/fifo_generator_v13_2_3
E:\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
E:\\Modelsim\\win64\\vmap blk_mem_gen_v8_4_2 modelsim_lib/msim/blk_mem_gen_v8_4_2

E:\\Modelsim\\win64\\vlog -64 -incr -work fifo_generator_v13_2_3  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" \
"../../../../SRC_System.ip_user_files/ipstatic/simulation/fifo_generator_vlog_beh.v" \

E:\\Modelsim\\win64\\vcom -64 -93 -work fifo_generator_v13_2_3  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.vhd" \

E:\\Modelsim\\win64\\vlog -64 -incr -work fifo_generator_v13_2_3  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.v" \

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" \
"../../../../SRC_System.srcs/sources_1/ip/fifo_out/sim/fifo_out.v" \
"../../../../SRC_System.srcs/sources_1/ip/fifo_0/sim/fifo_0.v" \

E:\\Modelsim\\win64\\vlog -64 -incr -work blk_mem_gen_v8_4_2  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" \
"../../../../SRC_System.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" \
"../../../../SRC_System.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_clk_wiz.v" \
"../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.v" \
"../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_clk_wiz.v" \
"../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.v" \
"../../../../SRC_System.srcs/sources_1/new/clk_88_2KHz.v" \
"../../../../SRC_System.srcs/sources_1/new/clk_88_2KHz_to_11_025KHz.v" \
"../../../../SRC_System.srcs/sources_1/new/clk_96KHz.v" \
"../../../../SRC_System.srcs/sources_1/new/clk_96KHz_to_12KHz.v" \
"../../../../SRC_System.srcs/sources_1/new/clk_div_8_82MHz_to_11_025KHz.v" \
"../../../../SRC_System.srcs/sources_1/new/clk_div_9_6MHz_to_12KHz.v" \
"../../../../SRC_System.srcs/sources_1/new/signal_interpolation_farrow_1.v" \
"../../../../SRC_System.srcs/sim_1/new/top_tb.v" \

# compile glbl module
E:\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

