######################################################################
#
# File name : top_tb_simulate.do
# Created on: Thu Apr 21 16:23:40 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L fifo_generator_v13_2_3 -L xil_defaultlib -L blk_mem_gen_v8_4_2 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.top_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {top_tb_wave.do}

view wave
view structure
view signals

do {top_tb.udo}

run 1000ns
