######################################################################
#
# File name : top_tb_compile.do
# Created on: Thu Apr 14 20:42:36 +0800 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\Modelsim\\win64\\vlib modelsim_lib/work
E:\\Modelsim\\win64\\vlib modelsim_lib/msim

E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xbip_utils_v3_0_9
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/axi_utils_v2_0_5
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xbip_pipe_v3_0_5
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xbip_dsp48_addsub_v3_0_5
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xbip_bram18k_v3_0_5
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/mult_gen_v12_0_14
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/floating_point_v7_0_15
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xbip_dsp48_mult_v3_0_5
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xbip_dsp48_multadd_v3_0_5
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/div_gen_v5_1_14
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/fifo_generator_v13_2_3
E:\\Modelsim\\win64\\vlib modelsim_lib/msim/blk_mem_gen_v8_4_2

E:\\Modelsim\\win64\\vmap xbip_utils_v3_0_9 modelsim_lib/msim/xbip_utils_v3_0_9
E:\\Modelsim\\win64\\vmap axi_utils_v2_0_5 modelsim_lib/msim/axi_utils_v2_0_5
E:\\Modelsim\\win64\\vmap xbip_pipe_v3_0_5 modelsim_lib/msim/xbip_pipe_v3_0_5
E:\\Modelsim\\win64\\vmap xbip_dsp48_wrapper_v3_0_4 modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_4
E:\\Modelsim\\win64\\vmap xbip_dsp48_addsub_v3_0_5 modelsim_lib/msim/xbip_dsp48_addsub_v3_0_5
E:\\Modelsim\\win64\\vmap xbip_bram18k_v3_0_5 modelsim_lib/msim/xbip_bram18k_v3_0_5
E:\\Modelsim\\win64\\vmap mult_gen_v12_0_14 modelsim_lib/msim/mult_gen_v12_0_14
E:\\Modelsim\\win64\\vmap floating_point_v7_0_15 modelsim_lib/msim/floating_point_v7_0_15
E:\\Modelsim\\win64\\vmap xbip_dsp48_mult_v3_0_5 modelsim_lib/msim/xbip_dsp48_mult_v3_0_5
E:\\Modelsim\\win64\\vmap xbip_dsp48_multadd_v3_0_5 modelsim_lib/msim/xbip_dsp48_multadd_v3_0_5
E:\\Modelsim\\win64\\vmap div_gen_v5_1_14 modelsim_lib/msim/div_gen_v5_1_14
E:\\Modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
E:\\Modelsim\\win64\\vmap fifo_generator_v13_2_3 modelsim_lib/msim/fifo_generator_v13_2_3
E:\\Modelsim\\win64\\vmap blk_mem_gen_v8_4_2 modelsim_lib/msim/blk_mem_gen_v8_4_2

E:\\Modelsim\\win64\\vcom -64 -93 -work xbip_utils_v3_0_9  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work axi_utils_v2_0_5  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/axi_utils_v2_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work xbip_pipe_v3_0_5  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work xbip_dsp48_wrapper_v3_0_4  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work xbip_dsp48_addsub_v3_0_5  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work xbip_bram18k_v3_0_5  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work mult_gen_v12_0_14  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work floating_point_v7_0_15  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/floating_point_v7_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work xbip_dsp48_mult_v3_0_5  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work xbip_dsp48_multadd_v3_0_5  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work div_gen_v5_1_14  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/div_gen_v5_1_vh_rfs.vhd" \

E:\\Modelsim\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../SRC_System.srcs/sources_1/ip/div_gen_1/sim/div_gen_1.vhd" \

E:\\Modelsim\\win64\\vlog -64 -incr -work fifo_generator_v13_2_3  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_4" \
"../../../../SRC_System.ip_user_files/ipstatic/simulation/fifo_generator_vlog_beh.v" \

E:\\Modelsim\\win64\\vcom -64 -93 -work fifo_generator_v13_2_3  \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.vhd" \

E:\\Modelsim\\win64\\vlog -64 -incr -work fifo_generator_v13_2_3  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_4" \
"../../../../SRC_System.ip_user_files/ipstatic/hdl/fifo_generator_v13_2_rfs.v" \

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_4" \
"../../../../SRC_System.srcs/sources_1/ip/fifo_farrow_1/sim/fifo_farrow_1.v" \
"../../../../SRC_System.srcs/sources_1/ip/fifo_farrow_0/sim/fifo_farrow_0.v" \

E:\\Modelsim\\win64\\vlog -64 -incr -work blk_mem_gen_v8_4_2  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_4" \
"../../../../SRC_System.ip_user_files/ipstatic/simulation/blk_mem_gen_v8_4.v" \

E:\\Modelsim\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_0" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_1" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_2" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_3" "+incdir+../../../../SRC_System.srcs/sources_1/ip/clk_wiz_4" \
"../../../../SRC_System.srcs/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../SRC_System.srcs/sources_1/new/signal_interpolation_farrow.v" \
"../../../../SRC_System.srcs/sim_1/new/top_tb.v" \

# compile glbl module
E:\\Modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

