# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/XDC.xdc

# IP: ip/fifo_farrow_out/fifo_farrow_out.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_farrow_out || ORIG_REF_NAME==fifo_farrow_out} -quiet] -quiet

# IP: ip/fifo_farrow_1/fifo_farrow_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_farrow_1 || ORIG_REF_NAME==fifo_farrow_1} -quiet] -quiet

# IP: ip/fifo_farrow_0/fifo_farrow_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_farrow_0 || ORIG_REF_NAME==fifo_farrow_0} -quiet] -quiet

# IP: ip/data_waiting_area_1/data_waiting_area_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_waiting_area_1 || ORIG_REF_NAME==data_waiting_area_1} -quiet] -quiet

# IP: ip/data_waiting_area/data_waiting_area.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_waiting_area || ORIG_REF_NAME==data_waiting_area} -quiet] -quiet
