# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 8
set_param simulator.modelsimInstallPath E:/Modelsim/win64
create_project -in_memory -part xc7a100tfgg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.cache/wt [current_project]
set_property parent.project_path D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/No_desktop/FPGA_part/Graduation_project/SRC_System/ui_src/Extraction_location.coe
add_files D:/No_desktop/FPGA_part/Graduation_project/SRC_System/ui_src/sin_1K.coe
add_files D:/No_desktop/FPGA_part/Graduation_project/SRC_System/ui_src/coefdata.coe
read_verilog -library xil_defaultlib {
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/AD9226.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/AD9767.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/AD9767_1.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/algorithm_top.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_64KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_64KHz_to_8KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_88_2KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_88_2KHz_to_11_025KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_96KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_96KHz_to_12KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_div_6_4MHz_to_8KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_div_8_82MHz_to_11_025KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/clk_div_9_6MHz_to_12KHz.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/conversion_mode_sel.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/data_waiting_area_ctrl.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/data_waiting_area_ctrl_1.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/filter.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/fir_coefdata_ctrl.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/signal_extraction.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/signal_extraction_1.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/signal_interpolation.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/signal_interpolation_farrow.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/uart_data_decode.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/uart_recv.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/uart_send.v
  D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/new/system_top.v
}
read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_out/fifo_farrow_out.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_out/fifo_farrow_out.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_out/fifo_farrow_out_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_out/fifo_farrow_out_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_1/fifo_farrow_1.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_1/fifo_farrow_1.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_1/fifo_farrow_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_1/fifo_farrow_1_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_0/fifo_farrow_0.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_0/fifo_farrow_0.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_0/fifo_farrow_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/fifo_farrow_0/fifo_farrow_0_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/data_waiting_area_1/data_waiting_area_1.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/data_waiting_area_1/data_waiting_area_1_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/data_waiting_area/data_waiting_area.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/data_waiting_area/data_waiting_area_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_1/clk_wiz_1_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_2/clk_wiz_2_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_board.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3.xdc]
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/clk_wiz_3/clk_wiz_3_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/Extraction_location/Extraction_location.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/Extraction_location/Extraction_location_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/coefdata_rom/coefdata_rom.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/coefdata_rom/coefdata_rom_ooc.xdc]

read_ip -quiet D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
set_property used_in_implementation false [get_files -all d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/constrs_1/new/XDC.xdc
set_property used_in_implementation false [get_files D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/constrs_1/new/XDC.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xc7a100tfgg676-2 -flatten_hierarchy none -keep_equivalent_registers


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
