# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/coefdata_rom/coefdata_rom.xci
# IP: The module: 'coefdata_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/coefdata_rom/coefdata_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coefdata_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/coefdata_rom/coefdata_rom.xci
# IP: The module: 'coefdata_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/No_desktop/FPGA_part/Graduation_project/SRC_System/SRC_System.srcs/sources_1/ip/coefdata_rom/coefdata_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'coefdata_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
